# Generated by Django 3.2 on 2021-05-04 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0002_remove_cantor_my_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cantor',
            name='buy_CHF',
            field=models.FloatField(max_length=10),
        ),
        migrations.AlterField(
            model_name='cantor',
            name='buy_EUR',
            field=models.FloatField(max_length=10),
        ),
        migrations.AlterField(
            model_name='cantor',
            name='buy_GBP',
            field=models.FloatField(max_length=10),
        ),
        migrations.AlterField(
            model_name='cantor',
            name='buy_USD',
            field=models.FloatField(max_length=10),
        ),
        migrations.AlterField(
            model_name='cantor',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='cantor',
            name='rating',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='cantor',
            name='sell_CHF',
            field=models.FloatField(max_length=10),
        ),
        migrations.AlterField(
            model_name='cantor',
            name='sell_EUR',
            field=models.FloatField(max_length=10),
        ),
        migrations.AlterField(
            model_name='cantor',
            name='sell_GBP',
            field=models.FloatField(max_length=10),
        ),
        migrations.AlterField(
            model_name='cantor',
            name='sell_USD',
            field=models.FloatField(max_length=10),
        ),
        migrations.AlterField(
            model_name='cantor',
            name='website',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
