# Generated by Django 3.2 on 2021-05-04 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0003_auto_20210504_1730'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cantor',
            old_name='buy_CHF',
            new_name='buy',
        ),
        migrations.RenameField(
            model_name='cantor',
            old_name='buy_EUR',
            new_name='sell',
        ),
        migrations.RemoveField(
            model_name='cantor',
            name='buy_GBP',
        ),
        migrations.RemoveField(
            model_name='cantor',
            name='buy_USD',
        ),
        migrations.RemoveField(
            model_name='cantor',
            name='sell_CHF',
        ),
        migrations.RemoveField(
            model_name='cantor',
            name='sell_EUR',
        ),
        migrations.RemoveField(
            model_name='cantor',
            name='sell_GBP',
        ),
        migrations.RemoveField(
            model_name='cantor',
            name='sell_USD',
        ),
        migrations.AddField(
            model_name='cantor',
            name='currency',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
    ]
