# Generated by Django 3.2 on 2021-05-04 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0005_alter_cantor_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cantor',
            name='website',
            field=models.CharField(max_length=100),
        ),
    ]
