# Generated by Django 3.2 on 2021-05-04 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0006_alter_cantor_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cantor',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
