# Generated by Django 3.2 on 2021-05-04 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0007_alter_cantor_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cantor',
            name='buy',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cantor',
            name='sell',
            field=models.CharField(max_length=100),
        ),
    ]
