# Generated by Django 3.2 on 2021-05-04 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0008_auto_20210504_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cantor',
            name='date',
            field=models.CharField(max_length=100),
        ),
    ]
