# Generated by Django 3.2 on 2021-05-05 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0009_alter_cantor_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cantor',
            name='buy',
            field=models.FloatField(max_length=10),
        ),
        migrations.AlterField(
            model_name='cantor',
            name='sell',
            field=models.FloatField(max_length=10),
        ),
    ]
