# Generated by Django 3.2 on 2021-05-05 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0010_auto_20210505_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cantor',
            name='date',
            field=models.DateTimeField(max_length=100),
        ),
    ]
